Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authorize/',include('authorization.urls')),
    path('blog/',include('blog_site.urls')),
    path('exam/',include('exam.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Blog/authorization/urls.py
from django.urls import path
from . import views
app_name='authorization'

urlpatterns = [
    path('signup/',views.SignUp,name='signup'),
    path('login/',views.LoginUser,name='login'),
    path('logout/',views.LogoutUser,name='logout'),
    path('test/student/',views.student_register,name='student'),
]

Blog/blog_site/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('about/',views.About.as_view(),name='about'),
    path('',views.PostListView.as_view(),name='post_list'),
    path('drafts/',views.DraftListView.as_view(),name='drafts'),
    path('new/',views.PostCreateView,name='new_post'),
    path('detail/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(),name='post_update'),
    path('detail/<int:pk>/comment/',views.add_comments,name='add_comment'),
    path('publish/<int:pk>/',views.publish,name='publish'),
    path('detail/<int:pk>/comment/delete/',views.DeleteComment,name='delete_comment'),
    path('detail/<int:pk>/approve/',views.approve_comment,name='approve_comment'),
    path('detail/<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete'),
]

Blog/templates/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no">
    <title>Title</title>
    <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Nunito&family=PT+Sans+Narrow&family=Roboto:ital@1&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=PT+Sans+Narrow&family=Rambla:ital@1&family=Roboto:ital@1&display=swap" rel="stylesheet">
    <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <!-- Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>
      <!-- CSS -->
 <link rel="stylesheet" type="text/css" href="{% static 'css/master.css' %}">

    <!-- Fontasow -->
<link rel="stylesheet" type="text/css" href="{% static 'css/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'css/fontawesome.min.css' %}">
    <script src="{% static 'js/all.min.js' %}"></script>
    <script src="{% static 'js/fontawesome.min.js' %}"></script>

</head>
<body style="background-color:#f8f9fa">
<!-- Navbar -->
<nav class="navbar navbar-expand-lg p-4 nav-color">
    <!-- Blog.io -->
    <a class="navbar-brand nav-items" style="font-size:1.5rem;">Blog.io</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <i class="fas fa-bars"></i>
  </button>
    <!-- Blog.io items -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <a href="{% url 'blog:post_list' %}" class="nav-link nav-items">Welcome,{{ user }}</a>
            <li class="nav-item">
                <a href="{% url 'blog:new_post' %}" class="nav-link nav-items">New Post</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'blog:drafts' %}" class="nav-link nav-items">Drafts</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'blog:post_list' %}" class="nav-link nav-items">Posts</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'blog:about' %}" class="nav-link nav-items">About Us</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'authorization:logout' %}" class="nav-link nav-items">Logout</a>
            </li>
            {% else %}
            <li class="nav-item">
                <a href="{% url 'authorization:signup' %}" class="nav-link nav-items">SignUp</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'authorization:login' %}" class="nav-link nav-items">Login</a>
            </li>
            <li class="nav-item">
                <a href="{% url 'blog:about' %}" class="nav-link nav-items">About Us</a>
            </li>
            {% endif %}
        </ul>
    </div>
</nav>
<!-- End of Navbar -->
<div class="mt-5">
{% block body %}
{% endblock %}
</div>
</body>
</html>