Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authorize/',include('authorization.urls')),
    path('blog/',include('blog_site.urls')),
    path('exam/',include('exam.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Blog/blog_site/urls.py
from django.urls import path
from . import views
app_name = 'blog'

urlpatterns = [
    path('about/',views.About.as_view(),name='about'),
    path('',views.PostListView.as_view(),name='post_list'),
    path('drafts/',views.DraftListView.as_view(),name='drafts'),
    path('new/',views.PostCreateView,name='new_post'),
    path('detail/<int:pk>/',views.PostDetailView.as_view(),name='post_detail'),
    path('update/<int:pk>/',views.PostUpdateView.as_view(),name='post_update'),
    path('detail/<int:pk>/comment/',views.add_comments,name='add_comment'),
    path('publish/<int:pk>/',views.publish,name='publish'),
    path('detail/<int:pk>/comment/delete/',views.DeleteComment,name='delete_comment'),
    path('detail/<int:pk>/approve/',views.approve_comment,name='approve_comment'),
    path('detail/<int:pk>/delete/',views.PostDeleteView.as_view(),name='delete'),
]

Blog/blog_site/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils import timezone
from django.urls import reverse
# Create your models here.
class Post(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    title = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    published_date = models.DateTimeField(blank=True,null=True)

    def publish(self):
        self.published_date = timezone.now()
        self.save()

    def post_comment(self):
        return Comments.posts.filter(approved_commets=True)

    def get_absolute_url(self):
        return reverse('blog:post_list',kwargs={'pk':self.pk})

    def __str__(self):
        return self.title

class Comments(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,null=True,related_name='posts')
    author = models.CharField(max_length=200)
    text = models.TextField()
    created_date = models.DateTimeField(default=timezone.now)
    approved_comments = models.BooleanField(default=False)

    def approve_comments(self):
        self.approved_comments = True
        self.save()

    def get_absolute_url(self):
        return reverse('blog:post_list',kwargs={'pk':self.pk})

Blog/blog_site/views.py
from django.shortcuts import render,get_object_or_404,redirect,reverse
from django.urls import reverse_lazy
# Http imports
from  django.http import HttpResponseRedirect
# Models and forms import
from .models import Post,Comments
# Views import
from django.views.generic import TemplateView,ListView,DeleteView,UpdateView,DetailView,CreateView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.decorators import login_required
# Random imports
from django.utils import timezone
# Create your views here.
class About(TemplateView):
    template_name = 'blog_site/about.html'

class PostListView(ListView):
    model = Post

    def get_queryset(self):
        return Post.objects.filter(published_date__lte=timezone.now())

class DraftListView(LoginRequiredMixin,ListView):
    login_url = '/authorize/login/'
    model = Post
    template_name = 'blog_site/draft_list.html'
    def get_queryset(self):
        return Post.objects.filter(published_date__isnull=True).order_by('-created_date')

class PostDetailView(DetailView):
    model = Post

@login_required
def PostCreateView(request):
    if request.method == "POST":
        title = request.POST.get('title')
        text = request.POST.get('text')
        p = Post(user=request.user,title=title,text=text)
        p.save()
        return HttpResponseRedirect(reverse('blog:post_list'))
    return render(request,'blog_site/post_create.html')
@login_required
def publish(request,pk):
    post = get_object_or_404(Post,pk=pk)
    post.publish()
    return redirect('blog:post_list')

class PostUpdateView(LoginRequiredMixin,UpdateView):
    login_url = '/authorize/login/'
    model = Post
    fields = ('title','text')

class PostDeleteView(DeleteView,LoginRequiredMixin):
    login_url = 'authorize/login/'
    success_url = reverse_lazy('blog:post_list')
    model = Post
# Comments Views

def add_comments(request,pk):
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":

        author = request.POST.get('author')
        text = request.POST.get('text')

        c = Comments(post=post,author=author,text=text)
        c.save()
        return redirect('blog:post_detail',pk=post.pk)
    return render(request,'blog_site/comments.html')
@login_required
def DeleteComment(request,pk):
    comment = get_object_or_404(Comments,pk=pk)
    post_key = comment.post.pk
    comment.delete()                    # post_key saves the commet pk
    return redirect('blog:post_detail',pk=post_key)
@login_required
def approve_comment(request,pk):
    comment = get_object_or_404(Comments,pk)
    comment.approve_comments()
    return redirect('blog:post_detail',pk=comment.post.pk)

Blog/blog_site/templates/blog_site/about.html
{% extends 'index.html' %}
{% block body %}
<h1>I am in about page</h1>
{% endblock %}

Blog/blog_site/templates/blog_site/comments.html
{% extends 'index.html' %}
{% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="form-group">
            <label for="author">Author:-</label>
            <input type="text" class="form-control" name="author">
        </div>
        <div class="form-group">
            <label for="text">Text:-</label>
            <textarea name="text" class="form-control"></textarea>
        </div>
        <input type="submit" value="Comment" class="btn-default btn-outline-default">
    </form>
</div>

{% endblock %}

Blog/blog_site/templates/blog_site/draft_list.html
{% extends 'index.html' %}
{% block body %}


<div class="container">
    <div class="row">
        <div class="col col-sm-2 col-md-3 col-lg-4">
            <!-- Cards -->
            {% for post in post_list %}
            <div class="col">
            <div class="card card-body">
                <h2 class="card-title post-title"><a href="{% url 'blog:post_detail' pk=post.pk %}" class="titles1">{{ post.title }}</a></h2>
                <p class="card-text text-color para-post">{{ post.text|truncatewords_html:100 }}</p>
                <div>
                    <p class="font-weight-bold text-color"> Post Not published Yet!!!</p>
                    <button class="btn titles1" style="background-color:#1098F7"><a href="{% url 'blog:post_detail' pk=post.pk %}" class="text-light">More</a></button>

                </div>
                    <!-- End of Arrow -->
                </a>
            </div>
        </div>
            {% endfor %}
            <!-- End of Cards -->
        </div>
    </div>
</div>



{% endblock %}

Blog/blog_site/templates/blog_site/post_confirm_delete.html
{% extends 'index.html' %}
{% block body %}

<form method="POST">
    <h2 class="display-3">Do you want to delete this {{ object }}?</h2>
    <input type="submit" value="Delete" class="btn btn-danger">
    {% csrf_token %}
</form>






{% endblock %}

Blog/blog_site/templates/blog_site/post_create.html
{% extends 'index.html' %}
{% block body %}

<form method="POST">
    {% csrf_token %}
    <!-- Title input Group -->
    <div class="input-group p-4">

         <h3>Title:-</h3>
        <input type="text" placeholder="Enter the title of Post" class="form-control" name="title">
</div>


    <!-- End of title Input Group -->
    <!-- Text -->
    <div class="input-group p-4">
    <label for="text"><h3>Text:-</h3></label>
<textarea name="text" class="form-control" style="height:10rem"></textarea>
    </div>

    <input type="submit" value="Submit" class="btn btn-warning ml-5">
        <!-- End of Text -->

</form>



{% endblock %}

Blog/blog_site/templates/blog_site/post_detail.html
{% extends 'index.html' %}
{% block body %}
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
 <div class="container">
   <div class="row">
       <div class="col">
           <!--Start of the detail -->
           <div class="">Posted By:- <span class="roboto" style="font-size:2rem">{{ post.user }}</span>
             {% if request.user == post.user %}
               <div align=right class=""><a href="{% url 'blog:delete' pk=post.pk %}" class="btn btn-danger btn-outline-dark">Delete</a></div>
             {% endif %}
           </div>
           <div class="center roboto display-4">
<span class="">{{ post.title }}</span> <span class="date"> -{{ post.created_date }}</span>
           </div>
           <div class="container ml-3">
               <span class="para text-color">{{ post.text }}<p align=right> -{{ post.published_date }}</p></span>
           </div>


{% if post.published_date %}

           {% else %}
<a href="{% url 'blog:publish' pk=post.pk %}">Publish</a>
{% endif %}

{% if request.user == post.user %}
 <div class="m-4">
<H1>Do you want to delete this Post?</H1>
<a href="{% url 'blog:delete' pk=post.pk %}" class="btn btn-danger btn-outline-dark">Delete</a>
 </div>
{% endif %}
<!-- Start of comment -->
<h3>Comments:-</h3>
            <a href="{% url 'blog:add_comment' pk=post.pk %}" class="border-right-5 pt-3">Add comment
                    <!-- Arrow -->
                <svg width="1.4em" height="1.4em" viewBox="0 0 16 16" class="bi bi-arrow-right-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
                </svg> </a>
           {% if not post.posts.all %}
           <div class="jumbotron rounded">
               <div class="container">
                   <p class="lead"><b>No Comments Here<b></p>
               </div>
           </div>
           {% endif %}


{% for i in post.posts.all %}
           <div class="p-2 mt-4 rounded-lg mb-4" style="background-color:#dae4ee">
               <div class="mb-4 container">
                   <div class="border">
 <span class="font-weight-bold m-1">Author :- {{ i.author }}</span> <br>
       <hr class="my-1">
           <span class="ml-5 m-1">Comment :- {{ i.text }}</span><br>
           {% if request.user == post.user %}
  <a href="{% url 'blog:delete_comment' pk=i.pk%}">Delete</a>
           {% endif %}
                   </div>
               </div>
       </div>

{% endfor %}
<!-- End of comments -->
           <!-- End of the detail -->
       </div>
   </div>
 </div>
</body>
</html>

{% endblock %}

Blog/blog_site/templates/blog_site/post_form.html
{% extends 'index.html' %}
{% block body %}

<form method="POST">
    {{ form.as_p }}
    {% csrf_token %}
    <input type="submit" value="Update" class="btn btn-warning">
</form>



{% endblock %}

Blog/blog_site/templates/blog_site/post_list.html
{% extends 'index.html' %}
{% block body %}

<div class="container">

<div class="row">
    <!-- Timer -->
    <p id="demo"></p>
   <script>
// Set the date we're counting down to
var countDownDate = new Date("December 23, 2020 01:00:00").getTime();

// Update the count down every 1 second
var x = setInterval(function() {

  // Get today's date and time
  var now = new Date().getTime();

  // Find the distance between now and the count down date
  var distance = countDownDate - now;

  // Time calculations for days, hours, minutes and seconds
  var days = Math.floor(distance / (1000 * 60 * 60 * 24));
  var hours = Math.floor((distance % (1000 * 60 * 60 * 24)) / (1000 * 60 * 60));
  var minutes = Math.floor((distance % (1000 * 60 * 60)) / (1000 * 60));
  var seconds = Math.floor((distance % (1000 * 60)) / 1000);

  // Output the result in an element with id="demo"
  document.getElementById("demo").innerHTML = days + "d " + hours + "h "
  + minutes + "m " + seconds + "s ";

  // If the count down is over, write some text
  if (distance < 0) {
    clearInterval(x);
    document.getElementById("demo").innerHTML = "EXPIRED";
  }
}, 1000);
</script>

    <!-- End of Timer -->
            <!-- Posts -->
            {% for post in post_list %}

        <div class="col">
            <div class="card card-body">
                <h2 class="card-title post-title"><a href="{% url 'blog:post_detail' pk=post.pk %}" class="titles1">{{ post.title }}</a></h2>
                <p class="card-text text-color para-post">{{ post.text|truncatewords_html:100 }}</p>
                <div>
                    <p class="font-weight-bold text-color"> {{ post.published_date }}</p>
                    <button class="btn titles1" style="background-color:#1098F7"><a href="{% url 'blog:post_detail' pk=post.pk %}" class="text-light">More</a></button>

                </div>
                <a href="{% url 'blog:add_comment' pk=post.pk %}" class="border-right-5 pt-3">Add comment
                    <!-- Arrow -->
                <svg width="1.4em" height="1.4em" viewBox="0 0 16 16" class="bi bi-arrow-right-short" fill="currentColor" xmlns="http://www.w3.org/2000/svg">
  <path fill-rule="evenodd" d="M4 8a.5.5 0 0 1 .5-.5h5.793L8.146 5.354a.5.5 0 1 1 .708-.708l3 3a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708-.708L10.293 8.5H4.5A.5.5 0 0 1 4 8z"/>
</svg>
                    <!-- End of Arrow -->
                </a>
            </div>
        </div>

            {% endfor %}

    <!-- End of Posts -->
</div>

</div>



{% endblock %}