Blog/Blog/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('authorize/',include('authorization.urls')),
    path('blog/',include('blog_site.urls')),
    path('exam/',include('exam.urls')),
]
if settings.DEBUG:
        urlpatterns += static(settings.MEDIA_URL,
                              document_root=settings.MEDIA_ROOT)

Blog/exam/urls.py
from django.urls import path
from . import views
from django.conf import settings
from django.conf.urls.static import static
app_name = 'exam'

urlpatterns = [
    path('list/',views.ExamListView.as_view(),name='exam_list'),
    path('detail/<int:pk>/',views.ExamDetailView.as_view(),name='exam_detail'),
    path('new/',views.ExamCreateView,name='add_question'),
    path('',views.ExamPage.as_view(),name='exam_page'),
    path('detail/',views.ExamTarget.as_view(),name='exam_target'),
    path('index/',views.IndexView,name='index'),
    path('test/',views.NewTest,name='Test'),
    path('testlist/',views.TestListView.as_view(),name='test_list'),
    path('testdetail/<slug:slug>/<int:pk>/',views.TestDetailView.as_view(),name='test_detail'),
    path('testdelete/<int:pk>/',views.TestDeleteView.as_view(),name='test_delete'),
    path('testqusetiond/<int:pk>/',views.TestQuestionDelete,name='test_q_delete'),
    path('test/index/',views.TestIndex,name='test_index'),
    path('questions/list/',views.AllQuestions,name='question'),
    path('test/math/',views.NewMathsTest,name='maths_test'),
    path('test/physics/',views.NewPhysicsTest,name='physics_test'),
    path('test/chemistry/',views.NewChemistryTest,name='chemistry_test'),
    # Questions URL's
    path('test/maths/question/',views.question_maths,name='maths_question'),
    path('test/chemistry/question/',views.question_chemistry,name='chemistry_question'),
    path('test/physics/question/',views.question_physics,name='physics_question'),
    path('test/<int:pk>/question/',views.add_new_question_detail,name='add_question_detail'),
    # Student Register
    path('test/student/<int:pk>/',views.register,name='register'),
    path('test/student/list/',views.register_list,name='student_register'),
    path('test/student/11th/<int:pk>/',views.add_all_11th,name='add_11th'),
    # Endtest
    path('test/<int:pk>/end/',views.Endtest,name='end_test'),
]

Blog/exam/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from django.utils.text import slugify
from authorization.models import student_res
from django.contrib.auth.mixins import PermissionRequiredMixin
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Exam(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    subject = models.CharField(max_length=400,blank=True)
    question = models.CharField(max_length=3000)
    option1 = models.CharField(max_length=3000,blank=True)
    optionimg1 = models.ImageField(upload_to='photo/',blank=True,null=True)
    option2 = models.CharField(max_length=3000,blank=True)
    optionimg2 = models.ImageField(upload_to='photo/',blank=True,null=True)
    option3 = models.CharField(max_length=3000,blank=True)
    optionimg3 = models.ImageField(upload_to='photo/',blank=True,null=True)
    option4 = models.CharField(max_length=3000,blank=True)
    optionimg4 = models.ImageField(upload_to='photo/',blank=True,null=True)
    correct = models.CharField(max_length=3000,blank=True)
    correctimg = models.ImageField(upload_to='photo/',blank=True,null=True)



    def __str__(self):
        return self.question

    def get_absolute_url(self):
        return reverse('exam:exam_list')

cho = (('11th','11th'),('12th','12th'),('other','other'))

class Tests(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    std = models.CharField(max_length=30,choices=cho,blank=True,null=True)
    test_name = models.CharField(max_length=1000)
    test_approve = models.BooleanField(default=False)
    test_question = models.ForeignKey(Exam, on_delete=models.CASCADE,null=True)
    test_date = models.CharField(blank=True,null=True,max_length=500)
    test_subject = models.CharField(blank=True,null=True,max_length=300)
    test_time = models.CharField(blank=True,null=True,max_length=300)
    test_end_time = models.CharField(blank=True,null=True,max_length=20)
    slug = models.SlugField(unique=True,blank=True,null=True)

    def slugi(self):
        self.slug = slugify(self.test_name)
        return self.slug

    def get_absolute_url(self):
        return reverse('exam:test_detail',kwargs={'pk':self.pk,'slug':'slug'})

    def __str__(self):
        return self.test_name

class registers(models.Model):
    test = models.ForeignKey(Tests,on_delete=models.CASCADE,related_name='student_registers')
    student = models.ForeignKey(User,on_delete=models.CASCADE)
    time = models.CharField(default='59',max_length=200,null=True,blank=True)
    end_test = models.BooleanField(default=False)

class ExamAns(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    question = models.ForeignKey(Exam,on_delete=models.CASCADE,null=True,blank=True)
    store = models.CharField(max_length=3000, blank=True, null=True)
    test = models.ForeignKey(Tests,on_delete=models.CASCADE,null=True,blank=True)

Blog/exam/forms.py
from django import forms
from .models import Exam

class Examform(forms.ModelForm):
    class Meta:
        model = Exam
        fields =['question','option1','option2','option3','option4','optionimg1','optionimg2','optionimg3','optionimg4','correctimg']

Blog/exam/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse,reverse_lazy
import time
import datetime
# Http Imports

from django.http import HttpResponse,HttpResponseRedirect
# Time Imports
from django.utils.timezone import utc
from django.contrib.auth.models import User
import datetime

# Form imports

# Model Imports
from django.db.models import F
from authorization.models import student_res
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from .models import Exam,ExamAns,Tests,registers
# Class based Views imports
from django.views.generic import TemplateView,ListView,DetailView,CreateView,DeleteView
from django.views.generic.edit import FormMixin
from django.contrib.auth import get_user_model
# Create your views here.

def IndexView(request):
    return render(request,'index.html')

class ExamListView(LoginRequiredMixin,ListView):
    login_url = '/authorize/login/'
    model = Exam
    context_object_name = 'exam'


@login_required
def ExamCreateView(request):
    if request.method == 'POST':
        question = request.POST.get('question')
        option1 = request.POST.get('option1')
        option2 = request.POST.get('option2')
        option3 = request.POST.get('option3')
        option4 = request.POST.get('option4')
        correct = request.POST.get('correct')
        img1 = request.POST.get('img1')
        img2 = request.POST.get('img2')
        img3 = request.POST.get('img3')
        img4 = request.POST.get('img4')
        img5 = request.POST.get('img5')
        subject = request.POST.get('subject')
        exam_img = Exam(user=request.user,question=question,option1=option1,option2=option2,option3=option3,option4=option4,correct=correct,optionimg1=img1,optionimg2=img2,optionimg3=img3,optionimg4=img4,correctimg=img5,subject=subject)
        exam_img.save()
        return HttpResponseRedirect(reverse('exam:exam_list'))
    return render(request,'exam/exam_form.html')



class ExamDetailView(LoginRequiredMixin,DetailView):
    login_url = '/authorize/login/'
    model = Tests
    context_object_name = 'exam'
    template_name = 'exam/exam_detail.html'

    def post(self, request, pk,*args, **kwargs):
        store = request.POST.get('answer')
        ques = request.POST.get('question')
        test = get_object_or_404(Tests,pk=self.kwargs['pk'])
        exam = get_object_or_404(Exam,pk=test.test_question.pk)
        try:
            examans = ExamAns.objects.filter(user=request.user,question__exact=ques,store__isnull=False,test=test).values_list('id',flat=True)[0]
#       print(examans)
            examans_change = get_object_or_404(ExamAns,pk=examans)
#        print(examans_change)
            examans_change.store = store
            examans_change.save()
            if examans == 0:
                examans = ExamAns(user=request.user, question=exam, store=store,test=test)
                examans.save()
        except:
            examans = ExamAns(user=request.user,question=exam,store=store,test=test)
            examans.save()

        ti = get_object_or_404(Tests,pk=self.kwargs['pk'])
        r = registers.objects.filter(student=self.request.user,test=ti)[0]
        print(r)
        r.test_time = request.POST.get('time')
        r.save()
        return HttpResponseRedirect(reverse('test_list'))


class ExamPage(LoginRequiredMixin,TemplateView):
    login_url = '/authorize/login/'
    template_name = 'exam/exam_page.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['exam'] = Exam.objects.all()
        return context

class ExamTarget(LoginRequiredMixin,TemplateView):
    login_url = '/authorize/login/'
    template_name = 'exam/exam_target.html'
@login_required
def question_maths(request):
    test1 = Tests.objects.filter(user=request.user,test_subject='maths').values_list('id',flat=True)
    test1 = test1[len(test1)-1]
    test = get_object_or_404(Tests,pk=test1)
    if request.method == 'POST':
        question = request.POST.get('question')
        option1 = request.POST.get('option1')
        option2 = request.POST.get('option2')
        option3 = request.POST.get('option3')
        option4 = request.POST.get('option4')
        correct = request.POST.get('correct')
        img1 = request.POST.get('img1')
        img2 = request.POST.get('img2')
        img3 = request.POST.get('img3')
        img4 = request.POST.get('img4')
        img5 = request.POST.get('img5')

        exam_img = Exam(user=request.user,question=question,option1=option1,option2=option2,option3=option3,option4=option4,correct=correct,optionimg1=img1,optionimg2=img2,optionimg3=img3,optionimg4=img4,correctimg=img5,subject='maths')
        exam_img.save()
        n = Exam.objects.filter(user=request.user,question=question,subject='maths').values_list('id',flat=True)
        n = n[0]
        exam_test = get_object_or_404(Exam,pk=n)
        test2 = Tests(test_end_time=test.test_end_time,test_name=test.test_name,user=request.user,test_question=get_object_or_404(Exam,pk=n),test_subject='maths',test_date=test.test_date,test_time=test.test_time,test_approve=True)
        test2.save()
    return render(request,'test/question_maths.html',context={'sub':'Maths'})
@login_required
def NewMathsTest(request):
    questions = Exam.objects.filter(subject='maths')
    if request.method == "POST":
        text_name = request.POST['test_name']
        test_date = request.POST['test_date']
        test_time = request.POST['test_time']
        test_end = request.POST['test_end']
        try:
            if request.POST['qu']:
                text_name = request.POST['test_name']
                test_date = request.POST['test_date']
                test_time = request.POST['test_time']
                text_question = request.POST.getlist('qu')
                for i in range(len(text_question)):
                    test = Tests(test_subject='maths',user=request.user,test_end_time=test_end,test_date=test_date,test_time=test_time,test_name=text_name,test_approve=True,test_question=get_object_or_404(Exam,pk=text_question[i]))
                    test.save()
                test = Tests(test_subject='maths',user=request.user,test_end_time=test_end,test_date=test_date,test_time=test_time,test_name=text_name)
                test.save()
                r = registers(student=request.user,time="59:00",test=test)
                r.save()
        except:

            test = Tests(user=request.user,test_end_time=test_end,test_date=test_date,test_time=test_time,test_name=text_name,test_subject='maths')
            test.save()
        return HttpResponseRedirect(reverse('exam:maths_question'))

    return render(request,'test/test_maths.html',context={'questions':questions})
@login_required
def question_chemistry(request):
    test1 = Tests.objects.filter(user=request.user,test_subject='chemistry').values_list('id',flat=True)
    test1 = test1[len(test1)-1]
    test = get_object_or_404(Tests,pk=test1)
    if request.method == 'POST':
        question = request.POST.get('question')
        option1 = request.POST.get('option1')
        option2 = request.POST.get('option2')
        option3 = request.POST.get('option3')
        option4 = request.POST.get('option4')
        correct = request.POST.get('correct')
        img1 = request.POST.get('img1')
        img2 = request.POST.get('img2')
        img3 = request.POST.get('img3')
        img4 = request.POST.get('img4')
        img5 = request.POST.get('img5')

        exam_img = Exam(user=request.user,question=question,option1=option1,option2=option2,option3=option3,option4=option4,correct=correct,optionimg1=img1,optionimg2=img2,optionimg3=img3,optionimg4=img4,correctimg=img5,subject='chemistry')
        exam_img.save()
        n = Exam.objects.filter(user=request.user,question=question,subject='chemistry').values_list('id',flat=True)
        print(n)
        n = n[0]
        exam_test = get_object_or_404(Exam,pk=n)
        test2 = Tests(test_name=test.test_name,user=request.user,test_question=get_object_or_404(Exam,pk=n),test_subject='chemistry',test_date=test.test_date,test_time=test.test_time,test_approve=True,test_end_time=test.test_end_time)
        test2.save()
    return render(request,'test/question_maths.html',context={'sub':'Chemistry'})
@login_required
def NewChemistryTest(request):
    questions = Exam.objects.filter(subject='chemistry')
    if request.method == "POST":
        text_name = request.POST['test_name']
        test_date = request.POST['test_date']
        test_time = request.POST['test_time']
        test_end = request.POST['test_end']
        try:
            if request.POST['qu']:
                text_name = request.POST['test_name']
                test_date = request.POST['test_date']
                test_time = request.POST['test_time']
                text_question = request.POST.getlist('qu')
                for i in range(len(text_question)):
                    test = Tests(user=request.user, test_end_time=test_end, test_date=test_date, test_time=test_time,
                                 test_name=text_name, test_approve=True,
                                 test_question=get_object_or_404(Exam, pk=text_question[i]),test_subject='chemistry')
                    test.save()
                test = Tests(test_subject='chemistry', user=request.user, test_end_time=test_end, test_date=test_date,
                             test_time=test_time, test_name=text_name)
                test.save()
                r = registers(student=request.user, time="59:00", test=test)
                r.save()
        except:

            test = Tests(user=request.user, test_end_time=test_end, test_date=test_date, test_time=test_time,
                         test_name=text_name, test_subject='chemistry')
            test.save()
        return HttpResponseRedirect(reverse('exam:chemistry_question'))

Blog/exam/templates/exam/exam_detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
        <!-- Google Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Roboto:ital@1&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=Nunito&family=PT+Sans+Narrow&family=Roboto:ital@1&display=swap" rel="stylesheet">

    <link rel="preconnect" href="https://fonts.gstatic.com">
<link href="https://fonts.googleapis.com/css2?family=PT+Sans+Narrow&family=Rambla:ital@1&family=Roboto:ital@1&display=swap" rel="stylesheet">
     <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
    <!-- End of Bootstrap -->
    <!-- Css -->
    <link rel="stylesheet" type="text/css" href="{% static 'css/exam.css' %}">
</head>
<body>
<div class="container">
    <div class="rows">
       <div class="col">

<form method="POST">
    {% csrf_token %}

    <h3 name="question" class="roboto">Q) <span>{{ exam.test_question.question }}</span></h3>

<div>
    {% if exam.test_question.optionimg1 %}
    <input type="radio" value="a" name="answer" class="form-check-input"><img src="{{exam.test_question.optionimg1.url}}"><br>
    {% else %}
    <input type="radio" value='{{ exam.test_question.option1 }}' name="answer" class="form-check-input"> {{ exam.test_question.option1 }}<br>
    {% endif %}
</div>
    <div>
    {% if exam.test_question.optionimg2 %}
    <input type="radio" value="b" name="answer" class="form-check-input"><img src="{{exam.optionimg2.url}}"><br>
    {% else %}
    <input type="radio" value='{{exam.test_question.option2}}' name="answer" class="form-check-input" > {{ exam.test_question.option2 }}<br>
    {% endif %}
</div>
<div>
    {% if exam.test_question.optionimg3 %}
    <input type="radio" value="c" name="answer" class="form-check-input"><img src="{{exam.test_question.optionimg3.url}}">
    {% else %}
    <input type="radio" value='{{exam.test_question.option3}}' name="answer" class="form-check-input" > {{ exam.test_question.option3 }}<br>
    {% endif %}
</div>
    <div>
    {% if exam.test_question.optionimg4 %}
    <input type="radio" value="d" name="answer" class="form-check-input"><img src="{{exam.test_question.optionimg4.url}}"><br>
    {% else %}
    <input type="radio" value='{{exam.test_question.option4}}' name="answer" class="form-check-input" > {{ exam.test_question.option4 }}<br>
    {% endif %}
</div>
    <input type="submit" value="Submit" class="btn btn-primary" name="time">
</form>
       </div>
            </div>

</div>
</body>
</html>

Blog/exam/templates/exam/exam_form.html
{% extends 'test/index_test.html' %}
{% block nav %}

<div class="container bg-light p-5">
    <div class="row">
        <div class="col text-center">
            <!-- Title -->
            <p class="test-list-title h2 pb-4">Add a new Question Globally or To your Personal Question Set!!</p>
            <!-- End of title -->
        </div>
    </div>

<form method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    <div class="form-group row text-center justify-content-center">
        <label for="question" class="col-sm-3 col-lg-2 col-form-label new-question" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Question:-</label>
        <div class="col-sm-6 col-lg-7">
            <input type="text" name="question" class="form-control">
        </div>
    </div>
    <div class="form-group row text-center justify-content-center">
        <label for="option1" class="col-sm-3 col-lg-2 col-form-label new-question" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Option1:-</label>
        <div class="col-sm-6 col-lg-7">
            <input type="text" name="option1" class="form-control">
        </div>
    </div>

    <div class="form-group row text-center justify-content-center">
        <label for="option1" class="col-sm-3 col-lg-2 col-form-label new-question" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Option2:-</label>
        <div class="col-lg-7 col-sm-6">
            <input type="text" name="option2" class="form-control">
        </div>
    </div>

    <div class="form-group row text-center justify-content-center">
        <label for="option1" class="col-sm-3 col-lg-2 col-form-label new-question" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Option3:-</label>
        <div class="col-sm-6 col-lg-7">
            <input type="text" name="option3" class="form-control">
        </div>
    </div>

    <div class="form-group row text-center justify-content-center">
        <label for="option1" class="col-sm-3 col-lg-2 col-form-label new-question" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Option4:-</label>
        <div class="col-sm-6 col-lg-7">
            <input type="text" name="option4" class="form-control">
        </div>
    </div>

    <div class="form-group row text-center justify-content-center">
        <label for="option1" class="col-sm-3 col-lg-2 col-form-label new-question" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Correct Option:-</label>
        <div class="col-sm-6 col-lg-7">
            <input type="text" name="correct" class="form-control">
        </div>
    </div>

    <div class="form-group row text-center justify-content-center">
        <span class="col-lg-2 col-sm-3" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Option1 Image:-</span>
        <div class="custom-file col-lg-10 col-sm-6">
        <input type="file" class=custom-file-input name="img1" id="inputGroupFile01">
    <label class="custom-file-label" for="inputGroupFile01">Choose file</label>
  </div>
    </div>

<div class="form-group row text-center justify-content-center">
    <span class="col-lg-2 col-sm-3" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Option2 Image:-</span>

    <div class="custom-file col-lg-10 col-sm-6">
        <input type="file" class=custom-file-input name="img2" id="inputGroupFile02">
    <label class="custom-file-label" for="inputGroupFile02">Choose file</label>
  </div>
</div>

<div class="form-group row text-center justify-content-center">
    <span class="col-lg-2 col-sm-3" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Option3 Image:-</span>

    <div class="custom-file col-lg-10 col-sm-6">
        <input type="file" class=custom-file-input name="img3" id="inputGroupFile03">
    <label class="custom-file-label" for="inputGroupFile03">Choose file</label>
  </div>
</div>

    <div class="form-group row text-center justify-content-center">
        <span class="col-lg-2 col-sm-3" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Option4 Image:-</span>
        <div class="custom-file col-lg-10 col-sm-6">
        <input type="file" class=custom-file-input name="img1" id="inputGroupFile04">
    <label class="custom-file-label" for="inputGroupFile04">Choose file</label>
  </div>
    </div>

    <div class="form-group row text-center justify-content-center">
        <span class="col-lg-2 col-sm-3" style="font-family: 'Fira Sans', sans-serif;font-size:1.2rem;">Correct Image:-</span>
        <div class="custom-file col-lg-10 col-sm-6">
        <input type="file" class=custom-file-input name="img1" id="inputGroupFile05">
    <label class="custom-file-label" for="inputGroupFile05">Choose file</label>
  </div>
    </div>



<div class="input-group pt-3">
    <div class="input-group-prepend">
        <button type="button" class="btn btn-outline-secondary">Subject</button>
    </div>
    <select name="subject" class="custom-select">
        <option value="Physics">Physics</option>
        <option value="Chemistry">Chemistry</option>
        <option value="Maths">Maths</option>
        <option value="Boi">Bio</option>
        <option value="random">Random Question</option>
    </select>
</div>
<div class="text-center pt-5">
    <input type="submit" value="Submit" class="btn btn-warning btn-outline-dark text-center">
</div>

</form>

</div>

<!-- Start of Footer -->
<footer class="container-fluid footer-background p-5">
    <div class="row">
        <!-- Start of the info Page -->
        <div class="col-md-6 col-lg-6 col-10">
            <div class="text-center p-4">
                <i class="fab fa-asymmetrik fa-4x navbar-text-color"></i>
            </div>
            <div class="text-center p-3">
               <p class="footer-text"> Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora incidunt
                   et perferendis ratione quod accusamus sit dolor optio eveniet vero.
               </p>
            </div>
            <div class="">
                <p class="navbar-text-color text-center">
                    Read More <i class="fas fa-arrow-right"></i>
                </p>
            </div>
        </div>
        <!-- End of the info Page -->
        <!-- Start of Contact Page -->
        <div class="col-md-6 col-lg-6 col-10">
            <div class="text-center p-4">
                <h2 class="footer-contact-text test-font">Contact</h2>
            </div>
          <!-- Start of Address -->
            <div class="d-flex justify-content-between my-5">
                <i class="fas fa-map navbar-text-color"></i>
                <span class="footer-text-color">
                    123 Main Street Veince,CA 90020
                </span>
            </div>
          <!-- End of Address -->
          <!-- Start of Phone -->
            <div class="d-flex justify-content-between my-5">
                <i class="fas fa-phone navbar-text-color"></i>
                <span class="footer-text-color">
                    +123 456 789
                </span>
            </div>
          <!-- End of Phone -->
          <!-- Start of Email -->
            <div class="d-flex justify-content-between my-5">
                <i class="fas fa-envelope navbar-text-color"></i>
                <span class="footer-text-color">
                    Email@Email.com
                </span>
            </div>
          <!-- End of Email -->
        </div>
        <!-- End of Contact Page -->
    </div>
</footer>
<!-- End of Footer -->
{% endblock %}

Blog/exam/templates/exam/exam_list.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'exam/exam_list.css' %}" type="text/css">
     <!-- Bootstrap -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
      <!-- Bootstrap JS -->
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.6/umd/popper.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"></script>

</head>
<body>
<script>var j=1;</script>
<div class="container">
    <div class="row">
<div class="col-md-6 col-lg-6 col-sm-3">
            {% for i in exam %}

 <a href="{% url 'exam:exam_detail' pk=i.pk %}" target="window1" class="m-2"><script>document.write(j);</script></a>
    <script>j++;</script>
{% endfor %}
</div>
    </div>

</div>



{% block exam_list %}
{% endblock %}
</body>
</html>

Blog/exam/templates/exam/exam_page.html
{% include 'index.html' %}
<div class="container">
    <div class="row">
    <div class="col-lg-6 col-sm-6 col-md-6 p-2" style="height:500px">

        <iframe src="{% url 'exam:exam_list' %}" height="100%" width="100%"></iframe>

    </div>
        <div class="col-lg-6 col-sm-6 col-md-6 p-2" style="height:500px">
       <iframe src="{% url 'exam:exam_target' %}" name="window1" height="100%" width="100%"></iframe>
    </div>
    </div>
</div>

Blog/exam/templates/exam/exam_target.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>